#!/usr/bin/env sh

if [ ! -d ~/personal ]; then
  mkdir -p ~/personal
fi

if [ ! -d ~/Documents ]; then
  mkdir ~/Documents
fi

if [ ! -d ~/Downloads ]; then
  mkdir ~/Downloads
fi

if [ ! -d ~/Git/web ]; then
  mkdir -p ~/Git/web
fi

if [ ! -d ~/Git/vicgeentor ]; then
  mkdir -p ~/Git/vicgeentor
fi

if [ ! -d ~/mnt/windows ]; then
  mkdir -p ~/mnt/windows
fi

if [ ! -d ~/mnt/temp ]; then
  mkdir -p ~/mnt/temp
fi

if [ ! -d ~/mnt/ssh ]; then
  mkdir -p ~/mnt/ssh
fi
